### ISSUE TITLE
Translator does not preserve last known valid config

### ISSUE THREAD

**Issue by harveyxia** [solo-io/service-mesh-hub#1007]
**Describe the bug**
If a valid networking policy is updated so that it is invalid, the last known valid config is not preserved, resulting in deletion of translated outputs.

**To Reproduce**
Apply the following TrafficPolicy:

```yaml
apiVersion: networking.smh.solo.io/v1alpha2
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: mtls
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
      - name: reviews
        namespace: bookinfo
        clusterName: mgmt-cluster
  outlierDetection:
    baseEjectionTime: 900s
    consecutiveErrors: 1
    interval: 300s
```

Then update it to the following, which is invalid because `reviews2` doesn't exist:

```yaml
apiVersion: networking.smh.solo.io/v1alpha2
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: mtls
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
      - name: reviews
        namespace: bookinfo
        clusterName: mgmt-cluster
      - name: reviews2
        namespace: bookinfo
        clusterName: mgmt-cluster
  outlierDetection:
    baseEjectionTime: 900s
    consecutiveErrors: 1
    interval: 300s
```

Inspect the status of the `reviews.bookinfo.mgmt-cluster` TrafficTarget and observe that the applied TrafficPolicy no longer exists.

**Expected behavior**
The config from the first object should be preserved on the `reviews.bookinfo.mgmt-cluster` TrafficTarget.

**Additional context**
Add any other context about the problem here, e.g.
- Service Mesh Hub version: 0.8.1
- Kubernetes version:  1.17
