### ISSUE TITLE
Add note of root cert change in SMH 0.9.0

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/service-mesh-hub#1021]
SMH 0.9.0 and there is another breaking change that isn't listed

To have SMH generating the root cert, we were using the following object:
```
apiVersion: networking.smh.solo.io/v1alpha2
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: service-mesh-hub
spec:
  mtlsConfig:
    autoRestartPods: true
    shared:
      rootCertificateAuthority:
        generated: null
  federation: {}
  meshes:
  - name: istiod-istio-system-cluster1
    namespace: service-mesh-hub
  - name: istiod-istio-system-cluster2
    namespace: service-mesh-hub
```

And now, it's invalid and must be:
```
apiVersion: networking.smh.solo.io/v1alpha2
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: service-mesh-hub
spec:
  mtlsConfig:
    autoRestartPods: true
    shared:
      rootCertificateAuthority:
        generated: {}
  federation: {}
  meshes:
  - name: istiod-istio-system-cluster1
    namespace: service-mesh-hub
  - name: istiod-istio-system-cluster2
    namespace: service-mesh-hub
```

Also:
There are some links broken in the API reference
For example, in this page (https://docs.solo.io/service-mesh-hub/latest/reference/api/access_policy/) I can't click on any link
