### ISSUE TITLE
Supergloo docs are incorrect

### ISSUE THREAD

**Issue by derrickburns** [solo-io/service-mesh-hub#473]
The `Install` crd is outdated.
```
cat <<EOF | kubectl apply --filename -
apiVersion: supergloo.solo.io/v1
kind: Install
metadata:
  name: linkerd
spec:
  installationNamespace: linkerd
  mesh:
    linkerdMesh:
      enableAutoInject: true
      enableMtls: true
      linkerdVersion: stable-2.3.0
EOF
```
