### ISSUE TITLE
Traffic policy in multicluster communication doc uses wrong cluster names

### ISSUE THREAD

**Issue by rvennam** [solo-io/service-mesh-hub#606]
```
# make sure that your context is still pointing to the management plane cluster

kubectl apply -f - <<EOF
apiVersion: networking.zephyr.solo.io/v1alpha1
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: simple
spec:
  destinationSelector:
    serviceRefs:
      services:
        - cluster: management-plane
          name: reviews
          namespace: default
  trafficShift:
    destinations:
      - destination:
          cluster: remote-cluster
          name: reviews
          namespace: default
        weight: 75
      - destination:
          cluster: management-plane
          name: reviews
          namespace: default
        weight: 15
        subset:
          version: v1
      - destination:
          cluster: management-plane
          name: reviews
          namespace: default
        weight: 10
        subset:
          version: v2
EOF

```
management-plane -> management-cluster
remote-cluster -> new-remote-cluster
