### ISSUE TITLE
Multicluster documentation prereqs issues

### ISSUE THREAD

**Issue by rvennam** [solo-io/service-mesh-hub#610]
https://docs.solo.io/service-mesh-hub/latest/guides/multicluster_communication/
says:
`- we have just installed Istio as described in the “Installing Istio” guide`
^ Istio is only installed in the remote cluster. Not management cluster

`- two clusters running Istio have been registered as described in the top-level intro`
It doesn't show the registration of management cluster (only remote cluster)
```
meshctl cluster register \
  --remote-cluster-name management-cluster \
  --remote-context management-plane-context
```

`- the two meshes are grouped together in a Virtual Mesh`
That top-level intro page doesn't show grouping of two clusters with VirtualMesh. It only showed remote cluster.
```
#### Create Virtual Mesh
kubectl apply -f - <<EOF
apiVersion: networking.zephyr.solo.io/v1alpha1
kind: VirtualMesh
metadata:
  name: demo-virtual-mesh
  namespace: service-mesh-hub
spec:
  enforceAccessControl: false
  meshes:
  - name: istio-istio-system-new-remote-cluster
    namespace: service-mesh-hub
  - name: istio-istio-system-management-cluster
    namespace: service-mesh-hub
EOF
```
Finally, bookinfo needs to be uninstalled from remote cluster before proceeding as this page deploys a subset of the bookinfo workload
