### ISSUE TITLE
configStatus for VirtualMesh doesn't get cleared when things are fine

### ISSUE THREAD

**Issue by christian-posta** [solo-io/service-mesh-hub#660]
When creating a VirtualMesh, for some reason the meshes weren't validated and I got this in the VirtualMesh.Status

```
 status:
    accessControlEnforcementStatus:
      state: ACCEPTED
    certificateStatus:
      state: ACCEPTED
    configStatus:
      message: 'The following mesh refs are invalid: [. .]'
      state: INVALID
    federationStatus:
      state: ACCEPTED
```

`meshctl check` and the logs all looked fine. 

After attaching a debugger, it seemed the meshes were validated just fine, but this status flag never gets cleared

https://github.com/solo-io/service-mesh-hub/blob/20b4dd01bd1f3afaeb9fcfc9d375c6b10533a3cd/services/mesh-networking/pkg/validation/validation.go#L70

We should clear this `configStatus` field if things return to consistent and ACCEPTED
