### ISSUE TITLE
`meshctl demo init` doesn't work on linux

### ISSUE THREAD

**Issue by GrahamGoudeau** [solo-io/service-mesh-hub#692]
> the special DNS name host.docker.internal, which resolves to the internal IP address used by the host. This is for development purpose and will not work in a production environment outside of Docker Desktop for Mac.

https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds

**Comment by john-a-joyce** [comment]
A workaround is to create the kind clusters with a king such as this 
```apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatchesJson6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: "${HOSTIP}"
```
where host IP would be the node port for the kind cluster.

**Comment by tiswanso** [comment]
Additional workaround notes... 
If using the host IP address as the certSAN, you also need to add a host port mapping to the cluster control-plane node.  So, for a single node KinD cluster the full KinD config would be:

```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatchesJson6902:
- group: kubeadm.k8s.io
  version: v1beta2
  kind: ClusterConfiguration
  patch: |
    - op: add
      path: /apiServer/certSANs/-
      value: "${HOSTIP}"
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 6443
    hostPort: ${K8S_HOSTPORT}
    listenAddress: ${HOSTIP}
```

-  the certSAN only works if you also modify the KinD cluster kubeconfig's `server` value to replace `127.0.0.1:6443` with the value of the `<HOSTIP>:<K8S_HOSTPORT>` so that the host port to KinD node mapping works.

The alternative would be to use a string name (e.g. cluster name) in the certSAN setting instead of `$HOSTIP` and update the `/etc/hosts` on your machine with a mapping of the node IP of the KinD cluster node to that name.  You'd still need to update the `server` field of the kubeconfig.
