### ISSUE TITLE
Add `APPMESH_VIRTUAL_NODE_NAME` to MeshWorkload

### ISSUE THREAD

**Issue by harveyxia** [solo-io/service-mesh-hub#732]
Appmesh VirtualNode names must match the [APPMESH_VIRTUAL_NODE_NAME](https://docs.aws.amazon.com/app-mesh/latest/userguide/virtual_nodes.html) environment variable, defined on the `aws-appmesh-envoy` container, e.g.:

```
- env:
    - name: APPMESH_VIRTUAL_NODE_NAME
      value: mesh/harvey-appmesh/virtualNode/details-v1-default
    - name: APPMESH_PREVIEW
      value: "0"
    - name: ENVOY_LOG_LEVEL
      value: info
    - name: AWS_REGION
      value: us-east-2
    image: 840364872350.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.12.3.0-prod
    imagePullPolicy: IfNotPresent
    name: envoy
```

We need to record this info on the MeshWorkload object so it's available at translation time.
