### ISSUE TITLE
VirtualMesh issue

### ISSUE THREAD

**Issue by djannot** [solo-io/service-mesh-hub#737]
I've followed the instructions from https://docs.solo.io/service-mesh-hub/latest/guides/federate_identity/, but when running the command below, it wasn't returning anything:

```
kubectl --context remote-cluster-context \
get virtualmeshcertificatesigningrequest -n service-mesh-hub
```

I took a look at the logs of the `mesh-networking` pod and seen the following:

```
{"level":"error","ts":1590758333.682146,"logger":"mesh-networking","msg":"pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1alpha1.VirtualMesh: v1alpha1.VirtualMeshList.ListMeta: v1.ListMeta.TypeMeta: Kind: Items: []v1alpha1.VirtualMesh: v1alpha1.VirtualMesh.Spec: unmarshalerDecoder: json: cannot unmarshal bool into Go value of type types.VirtualMeshSpec_EnforcementPolicy, error found in #10 byte of ...|hared\":{}}}],\"kind\":|..., bigger context ...|ter\",\"namespace\":\"service-mesh-hub\"}],\"shared\":{}}}],\"kind\":\"VirtualMeshList\",\"metadata\":{\"continue\"|...","version":"0.5.0","stacktrace":"k8s.io/klog.ErrorDepth\n\t/go/pkg/mod/github.com/stefanprodan/klog@v0.0.0-20190418165334-9cbb78b20423/klog.go:218\nk8s.io/apimachinery/pkg/util/runtime.logError\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:114\nk8s.io/apimachinery/pkg/util/runtime.HandleError\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/runtime/runtime.go:108\nk8s.io/client-go/tools/cache.(*Reflector).Run.func1\n\t/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:153\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88\nk8s.io/client-go/tools/cache.(*Reflector).Run\n\t/go/pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:151\nk8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:54\nk8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:71"}
````

I've tried editing the `VirtualMesh` object to add `EnforcementPolicy: MESH_DEFAULT` to the object, but still had the same issue.

Any idea ?

**Comment by harveyxia** [comment]
Hi @djannot, thanks for raising this issue. As you pointed out, the v0.5.0 release updates the `VirtualMesh` to use [an enum](https://docs.solo.io/service-mesh-hub/latest/reference/api/virtual_mesh/) for the `VirtualMeshSpec.EnforcementPolicy` field.

I just tested with the following VirtualMesh spec and it appears to work:

```
apiVersion: networking.zephyr.solo.io/v1alpha1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: service-mesh-hub
spec:
  displayName: "Demo Mesh Federation"
  certificateAuthority:
    builtin:
      ttlDays: 356
      rsaKeySizeBytes: 4096
      orgName: "service-mesh-hub"
  federation: 
    mode: PERMISSIVE
  shared: {}
  enforceAccessControl: MESH_DEFAULT
  meshes:
  - name: istio-istio-system-management-plane 
    namespace: service-mesh-hub
  - name: istio-istio-system-new-remote-cluster
    namespace: service-mesh-hub
```

Can you try again and let me know what you see?
