### ISSUE TITLE
SMH always override Istio's cacerts

### ISSUE THREAD

**Issue by namm2** [solo-io/service-mesh-hub#786]
Hi, I've installed SMH to have a virtual services mesh between 2 Istio v1.5 clusters, but got some issues with mutual TLS certs. Steps that I did:

- Generate SSL CA certs 
- Create generic secret cacerts
- Install Istio v1.5 by Helm 2 on both clusters (https://github.com/istio/istio/blob/1.5.4/install/kubernetes/helm/istio/example-values/values-istio-multicluster-gateways.yaml)
- Install SMH v0.5.0 on 1 cluster with the provided cert

```yaml
apiVersion: networking.zephyr.solo.io/v1alpha1
kind: VirtualMesh
metadata:
  name: virtual-mesh
  namespace: service-mesh-hub
spec:
  displayName: "Demo Mesh Federation"
  certificateAuthority:
    provided:
      certificate:
        name: cacerts
        namespace: istio-system
  federation: 
    mode: PERMISSIVE
  shared: {}
  enforceAccessControl: DISABLED
  meshes:
  - name: istio-istio-system-management-plane
    namespace: service-mesh-hub
  - name: istio-istio-system-cluster1
    namespace: service-mesh-hub
```

Now Istio citadel got in crashing mode, checked cacerts and it's empty and type is `solo.io/ca-intermediate` instead of Opaque like I created before.

```
kubectl describe secrets cacerts -n istio-system
Name:         cacerts
Namespace:    istio-system
Labels:       <none>
Annotations:  <none>

Type:  solo.io/ca-intermediate

Data
====
ca-key.pem:      3243 bytes
cert-chain.pem:  0 bytes
key.pem:         0 bytes
root-cert.pem:   0 bytes
ca-cert.pem:     0 bytes
```
Not sure if I get the SMH guide correctly: https://docs.solo.io/service-mesh-hub/latest/guides/federate_identity/#creating-a-virtual-mesh

**Comment by harveyxia** [comment]
Hi Nam, there's a few issues here when providing a root cert:

1. The provided root cert must have a different name/namespace than "cacerts/istio-system" because "cacerts/istio-system" is used by Service Mesh Hub 

2. The root cert must be represented as a Secret in a specific format:

```
kind: Secret
metadata:
  name: providedrootcert
  namespace: default
type: Opaque
data:
  key.pem: {private key file}
  root-cert.pem: {root CA certificate file}
```

I've updated the docs with the [specific steps](https://docs.solo.io/service-mesh-hub/latest/guides/federate_identity/#user-provided-certificates), give it a try and let me know if it works for you. Thanks!
