### ISSUE TITLE
fix protoc version mismatch causing segfault

### ISSUE THREAD

**Issue by ashleywang1** [solo-io/service-mesh-hub#951]
**Describe the bug**

When hitting the smh-apiserver and trying to list an AccessPolicy, we hit a segfault:
```
panic: runtime error: index out of range [0] with length 0
```
due to some enum value that was not filled in:

```
goroutine 484 [running]:
google.golang.org/protobuf/internal/filedesc.(*EnumValues).Get(0xc000368f80, 0x0, 0x0, 0x0)
        /Users/ashwang/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/filedesc/desc_list_gen.go:66 +0x5c
google.golang.org/protobuf/internal/impl.newEnumConverter(0x2f76180, 0x2a44ac0, 0x2f76060, 0xc0007a02a0, 0x0, 0x0)
        /Users/ashwang/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/convert.go:379 +0xde
google.golang.org/protobuf/internal/impl.newSingularConverter(0x2f76180, 0x2a44ac0, 0x2f76060, 0xc0007a02a0, 0x0, 0x0)
```

This turned out to be due to the following line in api/networking/v1alpha2/access_policy.proto:
```
/*
        Optional. A list of HTTP methods to allow (e.g., "GET", "POST").
        It is ignored in gRPC case because the value is always "POST".
        If not specified, allows any method.
    */
    repeated networking.smh.solo.io.HttpMethodValue allowed_methods = 5;
```

**To Reproduce**
1. Install the smh demo:
`meshctl demo istio-multicluster cleanup; meshctl demo istio-multicluster init`

2. kube apply:
```

apiVersion: networking.smh.solo.io/v1alpha2
kind: AccessPolicy
metadata:
  namespace: service-mesh-hub
  name: productpage
spec:
  sourceSelector:
  - kubeServiceAccountRefs:
      serviceAccounts:
        - name: bookinfo-productpage
          namespace: bookinfo
          clusterName: mgmt-cluster
  destinationSelector:
  - kubeServiceMatcher:
      namespaces:
      - bookinfo
```
3. (only for devs) - run the apiserver and the go client attempting to ListPolicies.

Pull down the service-mesh-hub-ui directory and check out the `fix-access-policy-segfault` branch.

4. Put a breakpoint on the ListPolicies function in the policies/handler.go file.
Run - in Goland, both the `services/smh-apiserver/cmd/main.go` apiserver file

5. Put a breakpoint somewhere in the `test/go_client/apiserver_go_clients.go` apiserver client (for dev use) file and run it as well.

6. See the error.

**Expected behavior**

Like in the trafficpolicy.proto, there should be a nillable wrapper:
```

    /*
        Optional. A list of HTTP methods to allow (e.g., "GET", "POST").
        It is ignored in gRPC case because the value is always "POST".
        If not specified, allows any method.
        Wrapping it in a nillable message.
    */
    HttpMethods allowed_methods = 5;
    message HttpMethods {
        repeated networking.smh.solo.io.HttpMethodValue allowed_methods = 1;
    }
```
