### ISSUE TITLE
Adding a subset option to failoverServiceRef

### ISSUE THREAD

**Issue by djannot** [solo-io/service-mesh-hub#953]
**Is your feature request related to a problem? Please describe.**
It's possible to create a `TrafficPolicy` with both `kubeService` and `failoverServiceRef` destinations, but the `failoverServiceRef` doesn't have a subset option, so we can't spread the local requests between several versions

**Describe the solution you'd like**
Being able to create a `TrafficPolicy` like that:
```
apiVersion: networking.smh.solo.io/v1alpha2
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: simple
spec:
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: kind2
          name: reviews
          namespace: default
  trafficShift:
    destinations:
      - kubeService:
          clusterName: kind3
          name: reviews
          namespace: default
          subset:
            version: v3
        weight: 75
      - failoverServiceRef:
          name: reviews-failover
          namespace: service-mesh-hub
          subset:
            version: v1
        weight: 15
      - failoverServiceRef:
          name: reviews-failover
          namespace: service-mesh-hub
          subset:
            version: v2
        weight: 15
```
