### ISSUE TITLE
Panic in Istio virtual service translation

### ISSUE THREAD

**Issue by joekelley** [solo-io/service-mesh-hub#979]
**Describe the bug**
I encountered a panic when applying a traffic policy with a non-empty source selector. The panic occurs here: https://github.com/solo-io/service-mesh-hub/blob/275e9c682faca1aadf479ff5c3b05f9cc3d52b21/pkg/mesh-networking/translation/istio/traffictarget/virtualservice/http_route_ordering.go#L41

```shell
panic: runtime error: index out of range [0] with length 0

goroutine 237 [running]:
github.com/solo-io/service-mesh-hub/pkg/mesh-networking/translation/istio/traffictarget/virtualservice.isHttpRouteMatcherMoreSpecific(0xc000c346c0, 0xc000c34180, 0x0)
	/workspace/service-mesh-hub/pkg/mesh-networking/translation/istio/traffictarget/virtualservice/http_route_ordering.go:44 +0x865
github.com/solo-io/service-mesh-hub/pkg/mesh-networking/translation/istio/traffictarget/virtualservice.RoutesBySpecificity.Less(0xc000c0f6a0, 0x3, 0x4, 0x2, 0x1, 0x0)
	/workspace/service-mesh-hub/pkg/mesh-networking/translation/istio/traffictarget/virtualservice/http_route_ordering.go:17 +0x77
sort.insertionSort(0x29c9960, 0xc000c0f6c0, 0x0, 0x3)
	/usr/local/go/src/sort/sort.go:27 +0x92
sort.quickSort(0x29c9960, 0xc000c0f6c0, 0x0, 0x3, 0x4)
	/usr/local/go/src/sort/sort.go:209 +0x2a9
sort.Sort(0x29c9960, 0xc000c0f6c0)
	/usr/local/go/src/sort/sort.go:218 +0x80
github.com/solo-io/service-mesh-hub/pkg/mesh-networking/translation/istio/traffictarget/virtualservice.(*translator).Translate(0xc000b3b460, 0x29f5a20, 0xc0002db900, 0xc000b67c00, 0x29d59e0, 0xc0006de600, 0x0)
	/workspace/service-mesh-hub/pkg/mesh-networking/translation/istio/traffictarget/virtualservice/virtual_service_translator.go:112 +0xc2e
github.com/solo-io/service-mesh-hub/pkg/mesh-networking/translation/istio/traffictarget.(*translator).Translate(0xc0006d3d00, 0x29f5a20, 0xc0002db900, 0xc000b67c00, 0x29fec60, 0xc0002358c0, 0x29d59e0, 0xc0006de600)
	/workspace/service-mesh-hub/pkg/mesh-networking/translation/istio/traffictarget/istio_traffic_target_translator.go:71 +0x12f
github.com/solo-io/service-mesh-hub/pkg/mesh-networking/translation/istio.(*istioTranslator).Translate(0xc00073d000, 0x29ce220, 0xc0006df0b0, 0x29f5a20, 0xc0002db900, 0x29fec60, 0xc0002358c0, 0x29d59a0, 0xc000b2fd10, 0x29d59e0, ...)
	/workspace/service-mesh-hub/pkg/mesh-networking/translation/istio/istio_networking_translator.go:59 +0x3f8
github.com/solo-io/service-mesh-hub/pkg/mesh-networking/translation.(*translator).Translate(0xc0006c3b00, 0x29ce220, 0xc0006de990, 0x29f5a20, 0xc0002db900, 0x29d59e0, 0xc0006de600, 0x0, 0x0, 0x0, ...)
	/workspace/service-mesh-hub/pkg/mesh-networking/translation/networking_translator.go:95 +0x57f
github.com/solo-io/service-mesh-hub/pkg/mesh-networking/apply.(*applier).Apply(0xc0005dc520, 0x29ce220, 0xc0006de5d0, 0x29f5a20, 0xc0002db900)
	/workspace/service-mesh-hub/pkg/mesh-networking/apply/applier.go:59 +0x733
github.com/solo-io/service-mesh-hub/pkg/mesh-networking/reconciliation.(*networkingReconciler).reconcile(0xc000629e00, 0x298fc20, 0xc0001a24e0, 0xc0005d0000, 0x0, 0x0)
	/workspace/service-mesh-hub/pkg/mesh-networking/reconciliation/networking_reconciler.go:89 +0x61d
github.com/solo-io/skv2/contrib/pkg/input.(*inputReconciler).processNextWorkItem(0xc0006c3e30, 0x0)
	/go/pkg/mod/github.com/solo-io/skv2@v0.11.1/contrib/pkg/input/input_reconciler.go:138 +0x1e0
github.com/solo-io/skv2/contrib/pkg/input.(*inputReconciler).reconcileEventsForever(0xc0006c3e30, 0x1dcd6500)
	/go/pkg/mod/github.com/solo-io/skv2@v0.11.1/contrib/pkg/input/input_reconciler.go:114 +0x31
created by github.com/solo-io/skv2/contrib/pkg/input.NewSingleClusterReconciler
	/go/pkg/mod/github.com/solo-io/skv2@v0.11.1/contrib/pkg/input/input_reconciler.go:81 +0x157
```

**To Reproduce**
Assuming you have istio running with bookinfo on both smh-mgmt and smh-remote, apply the following traffic policy:

**Edit** you need more than just this policy to reproduce; add another policy that selects on all sources.

```yaml
apiVersion: networking.smh.solo.io/v1alpha2
kind: TrafficPolicy
metadata:
  namespace: service-mesh-hub
  name: reviews-mirror
spec:
  sourceSelector:
    - labels:
        version: v1
  destinationSelector:
  - kubeServiceRefs:
      services:
        - clusterName: smh-mgmt
          name: reviews
          namespace: bookinfo
  mirror:
    kubeService:
      clusterName: smh-remote
      name: reviews
      namespace: bookinfo
    percentage: 1
    port: 9080

```

**Additional context**
SMH client and server 0.8.0, istio 1.6.8
